[build]
target = "aarch64-unknown-lucy.json"
rustflags = [
  "-l", "boot",
  "-C", "link-args=-n -Tlinker.ld -Ltarget"
]

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.aarch64-unknown-lucy]
linker = "aarch64-linux-gnu-ld"
