[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-args=-n --strip-all -Tuser/user.ld"
]

[unstable]
build-std = ["alloc", "core"]
build-std-features = ["panic_immediate_abort"]
