[build]
target = "x86_64-unknown-lucy.json"
rustflags = [
    "-L", "target",
    "-l", "boot",
    "-C", "link-args=-n -Tboot/linker.ld"
]

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]